name: Build Break Example
                                                                                                                                                                                                                                         
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
                                                                                                                                                                                                                                         
jobs:
  blackduck-scan:
    runs-on: [mac-arm-sh]
                                                                                                                                                                                                                                         
    steps:
    
    - name: Checkout Source
      uses: actions/checkout@v4
                                                                                                                                                                                                                                         
    - name: Black Duck Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        detect_args: "--detect.source.path=${{ github.workspace }}/nodejs-npm"
        blackducksca_scan_failure_severities: BLOCKER,CRITICAL

      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
